name: GitHub Self-service

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository Name'
        required: true
        type: text

jobs:
  create-repository:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO: ${{ github.event.inputs.repo-name }}

    steps:
        
      - name: Create Repository
        run: gh repo create $REPO --private add-readme --license MIT --gitignore Node

      - name: List Repositories
        run: gh repo list
