name: GitHub Self-service

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository Name'
        required: true
      project-name:
        description: 'Project Name'
        required: true
      clean-up:
        description: 'Clean up Resources'
        required: true
        type: boolean
        default: true

jobs:
  create-github:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO: ${{ github.event.inputs.repo-name }}
      PROJECT: ${{ github.event.inputs.project-name }}
      CLEAN_UP: ${{ github.event.inputs.clean-up }}

    steps:
        
      - name: Create Repo
        run: |
          REPO_NAME=$(gh repo create $REPO --public --add-readme --license MIT --gitignore Node)
          echo "CREATED_REPO=${REPO_NAME}" >> $GITHUB_ENV
        
      - name: View Repo
        run: gh repo view $CREATED_REPO

      - name: Enable Discussions
        run: gh repo edit $CREATED_REPO --enable-discussions

      - name: Create Project
        run: |
          PROJECT_DETAILS=$(gh project create --owner @me --title "$PROJECT" --format json)
          echo "PROJECT_NUMBER=$(echo "$PROJECT_DETAILS" | jq -r '.number')" >> $GITHUB_ENV
      
      - name: View Project
        run: gh project view $PROJECT_NUMBER --owner @me

      - name: Delete Repo
        if: ${{ env.CLEAN_UP == 'true' }}
        run: gh repo delete $CREATED_REPO --yes

      - name: Delete Project
        if: ${{ env.CLEAN_UP == 'true' }}
        run: gh project delete $PROJECT_NUMBER --owner "@me"