name: GitHub Self-service

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository Name'
        required: true
      project-name:
        description: 'Project Name'
        required: true

jobs:
  create-github:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO: ${{ github.event.inputs.repo-name }}
      PROJECT: ${{ github.event.inputs.project-name }}

    steps:
        
      - name: Create Repo
        run: |
          REPO_NAME=$(gh repo create $REPO --public --add-readme --license MIT --gitignore Node)
          echo "REPO_NAME: ${REPO_NAME}"
          echo "CREATED_REPO=${REPO_NAME}" >> $GITHUB_ENV

      - name: View Repository Name
        run: echo $CREATED_REPO
        
      - name: View Repo
        run: gh repo view $CREATED_REPO

      - name: Enable Discussions
        run: gh repo edit $CREATED_REPO --enable-discussions

      - name: Create Project
        run: |
          PROJECT_NUMBER=$(gh project create --owner @me --title "$PROJECT")
          echo "PROJECT_NUMBER: ${PROJECT_NUMBER}"
