name: GitHub Self-service

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Repository Name'
        required: true

jobs:
  create-repository:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      REPO: ${{ github.event.inputs.repo-name }}

    steps:
        
      - name: Create Repo
        run: CREATED_REPO=$(gh repo create $REPO --public --add-readme --license MIT --gitignore Node)

      - name: View Repository Name
        run: echo $CREATED_REPO
        
      - name: View Repo
        run: gh repo view $CREATED_REPO

      - name: Enable Discussions
        run: gh repo edit $CREATED_REPO --enable-discussions
